from environs import Env

env = Env()
env.read_env()

BOT_TOKEN = env.str('BOT_TOKEN')

STEAM_API_KEY = env.str('STEAM_API_KEY')
STEAM_LOGIN = env.str('STEAM_LOGIN')
STEAM_PASSWORD = env.str('STEAM_PASSWORD')

STEAM_FIRST_API_KEY = env.str('STEAM_FIRST_API_KEY')
STEAM_FIRST_LOGIN = env.str('STEAM_FIRST_LOGIN')
STEAM_FIRST_PASSWORD = env.str('STEAM_FIRST_PASSWORD')

STEAM_SECOND_API_KEY = env.str('STEAM_SECOND_API_KEY')
STEAM_SECOND_LOGIN = env.str('STEAM_SECOND_LOGIN')
STEAM_SECOND_PASSWORD = env.str('STEAM_SECOND_PASSWORD')

BINANCE_API_KEY = env.str('BINANCE_API_KEY')
BINANCE_SECRET_KEY = env.str('BINANCE_SECRET_KEY')

USER_BUY_PRICE = 1.68
USER_SELL_PRICE = 1.65

DB_USER = env.str('DB_USER')
DB_PASSWORD = env.str('DB_PASSWORD')
DB_HOST = env.str('DB_HOST')
